services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://host.docker.internal:5432/aldio
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
